name: Crawl

on:
  workflow_dispatch: {}
  schedule:
    # 5:30pm Pacific on M/W/F
    - cron: '30 0 * * 2,4,6'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: false

env:
  BROWSERTRIX_IMAGE: 'webrecorder/browsertrix-crawler:1.5.11'

jobs:
  crawl:
    runs-on: ubuntu-latest
    outputs:
      collection: ${{ steps.setup-collection.outputs.name }}
      collection_path: ${{ steps.setup-collection.outputs.path }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.CRAWLER_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CRAWLER_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Get Browsertrix-Crawler
        run: |
          docker pull '${{ env.BROWSERTRIX_IMAGE }}'

      - id: setup-collection
        run: |
          timestamp="$(date +'%Y%m%d%H%M%S')"

          # Important: double dash will be used later to make the name nicer.
          collection="test-crawl--${timestamp}"
          collection_path="crawls/collections/${collection}"
          echo "name=${collection}" >> "$GITHUB_OUTPUT"
          echo "path=${collection_path}" >> "$GITHUB_OUTPUT"

      - name: Get seeds
        run: |
          echo 'TODO: load seeds from DB'

      - name: Crawl
        run: |
          # TODO: use seeds from DB instead of this test set
          ./crawl.sh ./test.crawl.yaml '${{ steps.setup-collection.outputs.name }}'

      - name: Upload to S3
        run: |
          aws s3 cp --recursive \
            '${{ steps.setup-collection.outputs.path }}' \
            's3://${{ secrets.CRAWLER_S3_BUCKET }}/${{ steps.setup-collection.outputs.name }}'

      - name: Upload to workflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: crawl-output
          path: '${{ steps.setup-collection.outputs.path }}'
          retention-days: 7

  import-db:
    needs:
      - crawl
    runs-on: ubuntu-latest
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - uses: actions/download-artifact@v4
        with:
          name: crawl-output
          path: crawl

      - name: Import to web-monitoring-db
        env:
          WEB_MONITORING_DB_USER: '${{ secrets.WEB_MONITORING_DB_USER }}'
          WEB_MONITORING_DB_PASSWORD: '${{ secrets.WEB_MONITORING_DB_PASSWORD }}'
          WEB_MONITORING_DB_S3_BUCKET: '${{ secrets.WEB_MONITORING_DB_S3_BUCKET }}'
        run: |
          collection='${{ needs.crawl.outputs.collection }}'
          base_path='./crawl'

          uvx --from git+https://github.com/edgi-govdata-archiving/web-monitoring-processing wm-warc-import \
            --archive-s3 "${WEB_MONITORING_DB_S3_BUCKET}" \
            --seeds "${base_path}/crawls/config.${collection}.yaml" \
            --dry-run \
            ${base_path}/archive/*.warc.gz

  upload-ia:
    needs:
      - crawl
    runs-on: ubuntu-latest
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - uses: actions/download-artifact@v4
        with:
          name: crawl-output
          path: crawl

      # The IA CLI does not currently support env vars (it used to), so manually
      # write a config file.
      # See: https://github.com/jjjake/internetarchive/issues/640
      - name: Configure ia CLI
        run: |
          config_dir=~/.config/internetarchive
          mkdir -p $config_dir
          (
            echo '[s3]'
            echo 'access = ${{ secrets.IAS3_ACCESS_KEY }}'
            echo 'secret = ${{ secrets.IAS3_SECRET_KEY }}'
          ) > $config_dir/ia.ini

      - name: Upload to IA
        run: |
          collection='${{ needs.crawl.outputs.collection }}'
          base_path='./crawl'

          nice_name="$(
            echo "${collection}" \
            | sed -E 's/^(.*)--([0-9]{4})([0-9]{2})([0-9]{2}).*/\1/' \
            | sed -E 's/-/ /' \
            | sed -E 's/[[:alnum:]]+/\u&/g'
          )"
          iso_date="$(
            echo "${collection}" \
            | sed -E 's/^.*--([0-9]{4})([0-9]{2})([0-9]{2}).*/\1-\2-\3/'
          )"
          echo "title:${nice_name} ${iso_date}"
          # uvx --from internetarchive ia upload \
          #     --metadata="mediatype:web" \
          #     --metadata="title:${nice_name} ${iso_date}" \
          #     --metadata="date:${iso_date}" \
          #     "${collection}" \
          #     ${base_path}/archive/* \
          #     ${base_path}/logs/* \
          #     ${base_path}/pages/*
