name: Crawl

on:
  workflow_dispatch: {}
  schedule:
    # 5:30pm Pacific on M/W/F
    - cron: '30 0 * * 2,4,6'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: false

env:
  BROWSERTRIX_IMAGE: 'webrecorder/browsertrix-crawler:1.5.11'

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.CRAWLER_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CRAWLER_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Get Browsertrix-Crawler
        run: |
          docker pull '${{ env.BROWSERTRIX_IMAGE }}'

      - id: setup-collection
        run: |
          timestamp="$(date +'%Y%m%d%H%M%S')"

          collection="test-crawl-${timestamp}"
          collection_path="./crawls/collections/${collection}"
          echo "name=${collection}" >> "$GITHUB_OUTPUT"
          echo "path=${collection_path}" >> "$GITHUB_OUTPUT"

      - name: Get seeds
        run: |
          echo 'TODO: load seeds from DB instead of this test set'
          state_path='${{ steps.setup-collection.outputs.path}}/crawls/'
          mkdir -p "${state_path}"
          cp test.crawl.yaml "${state_path}"

      - name: Crawl
        run: |
          ./crawl.sh ./test.crawl.yaml '${{ steps.setup-collection.outputs.name }}'

      - name: Upload to S3
        run: |
          aws s3 cp --recursive \
            '${{ steps.setup-collection.outputs.path }}' \
            's3://${{ secrets.CRAWLER_S3_BUCKET }}/${{ steps.setup-collection.outputs.name }}'

      - name: Upload to workflow artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ${{ steps.setup-collection.outputs.path }}'
          retention-days: 7

  import-db:
    needs:
      - crawl
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'TODO: import to DB'

  upload-ia:
    needs:
      - crawl
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'TODO: upload to IA'
